### ISSUE TITLE
Auth API needs rethinking (again)

### ISSUE THREAD

**Issue by inca** [ubio/node-framework#69]
In my opinion, the latest round of changes around `AcAuthProvider` and `AcAuth` classes made the usage more awkward.

For example, consider the following diff:

![image](https://user-images.githubusercontent.com/118196/141061680-b16bc9c3-41d9-47f9-abff-d91dd7773e04.png)

Previously you'd specify _what_ your application wants to see in the auth object. Now you specify _some data_ that will somehow be parsed to achieve what your application wants to see. For the user of such API it's almost impossible to guess which data will result in which outcome without knowing the exact parsing algorithm. For example, if you need to emulate Service Account auth, you need to specify both `service_account_id` and `service_account_name` (because parser requires that).

Point being, the abstraction here is wrong. In test cases one should just say "I want a User of organisation" (e.g. `mockAuth.setUser('joe', orgId)`) or "I want a Service Account, optionally with organisation" (and the exact possible combinations should be fully supported by type system).

**Comment by kyungeunni** [comment]
How about extending the option `AcAuthSpec`  as follow? 

```ts
export type AcAuthSpec = {
    actor?: AcActor;
    jwtContext?: AcJwtContext,
};

export class AcAuth {
    actor: AcActor | null = null;

    constructor(spec: AcAuthSpec = {}) {
        if (spec.jwtContext) {
            this.actor = this.parseActor(spec.jwtContext);
        }
        if (spec.actor) {
            this.actor = spec.actor;
        }
    }
...
}
```

If both actor and jwtContext is provided as part of the AcAuthSpec option, `actor` will take precedence over `jwtContext`. When defining `actor` object, as soon as you assign value to `type`(it shows you enum), it infer the type of AcActor so that the type system will guide you through what properties are necessary for the type. 

`acAuth.set[Actor]` methods would require an extra step (1. instantiate AcAuth, 2. set the actor using the method) so it doesn't seem so helpful. Also it is difficult to imagine the use cases for an Application to change its actor explicitly so this extra helper method (such as setUser) doesn't seem to be a good fit - if we need this feature mostly for the tests, we can define AcMockAuthProvider that provide extra helper methods.
